let converter={"USD":1,"EUR":0.87,"RUB":66.25,"GBP":0.76}
let symbol={"USD":"$","EUR":"€","RUB":"₽","GBP":"£"}
let currencySelected=document.querySelector(".currency-selected span");let currencySelector=document.querySelector("#currency");let isMenuOpen=!1;let curToSelectList=document.querySelector(".currencies_to_select");let ethereumCheck=document.querySelector("#ethereumPercent");let litecoinCheck=document.querySelector("#litecoinPercent");let bitcoinCheck=document.querySelector("#bitcoinPercent");currencySelector.addEventListener("click",function(){if(isMenuOpen===!1){classRemoveAdd(curToSelectList,null,"open");isMenuOpen=!0}else{classRemoveAdd(curToSelectList,"open");isMenuOpen=!1}
priceCheck();percentsCheck()});getPriceUSD();for(let i=0;i<curToSelectList.children.length;i++){let element=curToSelectList.children[i];element.addEventListener("click",function(){let choosedCur=element.textContent;element.textContent=currencySelected.textContent;currencySelected.textContent=choosedCur;if(choosedCur=="USD")getPriceUSD();if(choosedCur=="EUR")getPriceEUR();if(choosedCur=="RUB")getPriceRUB();if(choosedCur=="GBP")getPriceGBP()})}
let priceSpan=document.querySelectorAll(".price span");function getPriceUSD(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){for(i=0;i<priceSpan.length;i++){priceSpan[i].textContent="$"+data.ask}})};function getPriceEUR(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){for(i=0;i<priceSpan.length;i++){priceSpan[i].textContent="€"+(data.ask*converter.EUR).toFixed(2)}})};function getPriceRUB(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){for(i=0;i<priceSpan.length;i++){priceSpan[i].textContent="₽"+(data.ask*converter.RUB).toFixed(2)}})};function getPriceGBP(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){for(i=0;i<priceSpan.length;i++){priceSpan[i].textContent="$"+(data.ask*converter.GBP).toFixed(2)}})};function getPercentsChangeEthereum(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){let hour=document.querySelector("#ethereum .Hour-change");let Day=document.querySelector("#ethereum .Day-change");let Week=document.querySelector("#ethereum .Week-change");let Month=document.querySelector("#ethereum .Month-change");hour.textContent=data.changes.percent.hour+"%";if(parseFloat(hour.textContent)<0){hour.style.color="red"}else if(parseFloat(hour.textContent)>0){hour.style.color="green";hour.textContent="+"+hour.textContent}
Day.textContent=data.changes.percent.day+"%";if(parseFloat(Day.textContent)<0){Day.style.color="red"}else if(parseFloat(Day.textContent)>0){Day.style.color="green";Day.textContent="+"+Day.textContent}
Week.textContent=data.changes.percent.week+"%";if(parseFloat(Week.textContent)<0){Week.style.color="red"}else if(parseFloat(Week.textContent)>0){Week.style.color="green";Week.textContent="+"+Week.textContent}
Month.textContent=data.changes.percent.month+"%";if(parseFloat(Month.textContent)<0){Month.style.color="red"}else if(parseFloat(Month.textContent)>0){Month.style.color="green";Month.textContent="+"+Month.textContent}})};function getPercentsChangeLitecoin(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){let hour=document.querySelector("#litecoin .Hour-change");let Day=document.querySelector("#litecoin .Day-change");let Week=document.querySelector("#litecoin .Week-change");let Month=document.querySelector("#litecoin .Month-change");hour.textContent=data.changes.percent.hour+"%";if(parseFloat(hour.textContent)<0){hour.style.color="red"}else if(parseFloat(hour.textContent)>0){hour.style.color="green";hour.textContent="+"+hour.textContent}
Day.textContent=data.changes.percent.day+"%";if(parseFloat(Day.textContent)<0){Day.style.color="red"}else if(parseFloat(Day.textContent)>0){Day.style.color="green";Day.textContent="+"+Day.textContent}
Week.textContent=data.changes.percent.week+"%";if(parseFloat(Week.textContent)<0){Week.style.color="red"}else if(parseFloat(Week.textContent)>0){Week.style.color="green";Week.textContent="+"+Week.textContent}
Month.textContent=data.changes.percent.month+"%";if(parseFloat(Month.textContent)<0){Month.style.color="red"}else if(parseFloat(Month.textContent)>0){Month.style.color="green";Month.textContent="+"+Month.textContent}})};function getPercentsChangeBitcoin(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){let hour=document.querySelector("#bitcoin .Hour-change");let Day=document.querySelector("#bitcoin .Day-change");let Week=document.querySelector("#bitcoin .Week-change");let Month=document.querySelector("#bitcoin .Month-change");hour.textContent=data.changes.percent.hour+"%";if(parseFloat(hour.textContent)<0){hour.style.color="red"}else if(parseFloat(hour.textContent)>0){hour.style.color="green";hour.textContent="+"+hour.textContent}
Day.textContent=data.changes.percent.day+"%";if(parseFloat(Day.textContent)<0){Day.style.color="red"}else if(parseFloat(Day.textContent)>0){Day.style.color="green";Day.textContent="+"+Day.textContent}
Week.textContent=data.changes.percent.week+"%";if(parseFloat(Week.textContent)<0){Week.style.color="red"}else if(parseFloat(Week.textContent)>0){Week.style.color="green";Week.textContent="+"+Week.textContent}
Month.textContent=data.changes.percent.month+"%";if(parseFloat(Month.textContent)<0){Month.style.color="red"}else if(parseFloat(Month.textContent)>0){Month.style.color="green";Month.textContent="+"+Month.textContent}})};function getPriceChangeEthereum(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){let hour=document.querySelector("#ethereum .Hour-change");let Day=document.querySelector("#ethereum .Day-change");let Week=document.querySelector("#ethereum .Week-change");let Month=document.querySelector("#ethereum .Month-change");hour.textContent=(data.changes.price.hour*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(hour.textContent)<0){hour.style.color="red"}else if(parseFloat(hour.textContent)>0){hour.style.color="green";hour.textContent="+"+hour.textContent}
Day.textContent=(data.changes.price.day*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Day.textContent)<0){Day.style.color="red"}else if(parseFloat(Day.textContent)>0){Day.style.color="green";Day.textContent="+"+Day.textContent}
Week.textContent=(data.changes.price.week*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Week.textContent)<0){Week.style.color="red"}else if(parseFloat(Week.textContent)>0){Week.style.color="green";Week.textContent="+"+Week.textContent}
Month.textContent=(data.changes.price.month*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Month.textContent)<0){Month.style.color="red"}else if(parseFloat(Month.textContent)>0){Month.style.color="green";Month.textContent="+"+Month.textContent}})};function getPriceChangeLitecoin(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){let hour=document.querySelector("#litecoin .Hour-change");let Day=document.querySelector("#litecoin .Day-change");let Week=document.querySelector("#litecoin .Week-change");let Month=document.querySelector("#litecoin .Month-change");hour.textContent=(data.changes.price.hour*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(hour.textContent)<0){hour.style.color="red"}else if(parseFloat(hour.textContent)>0){hour.style.color="green";hour.textContent="+"+hour.textContent}
Day.textContent=(data.changes.price.day*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Day.textContent)<0){Day.style.color="red"}else if(parseFloat(Day.textContent)>0){Day.style.color="green";Day.textContent="+"+Day.textContent}
Week.textContent=(data.changes.price.week*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Week.textContent)<0){Week.style.color="red"}else if(parseFloat(Week.textContent)>0){Week.style.color="green";Week.textContent="+"+Week.textContent}
Month.textContent=(data.changes.price.month*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Month.textContent)<0){Month.style.color="red"}else if(parseFloat(Month.textContent)>0){Month.style.color="green";Month.textContent="+"+Month.textContent}})};function getPriceChangeBitcoin(){$.getJSON('https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD').done(function(data){let hour=document.querySelector("#bitcoin .Hour-change");let Day=document.querySelector("#bitcoin .Day-change");let Week=document.querySelector("#bitcoin .Week-change");let Month=document.querySelector("#bitcoin .Month-change");hour.textContent=(data.changes.price.hour*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(hour.textContent)<0){hour.style.color="red"}else if(parseFloat(hour.textContent)>0){hour.style.color="green";hour.textContent="+"+hour.textContent}
Day.textContent=(data.changes.price.day*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Day.textContent)<0){Day.style.color="red"}else if(parseFloat(Day.textContent)>0){Day.style.color="green";Day.textContent="+"+Day.textContent}
Week.textContent=(data.changes.price.week*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Week.textContent)<0){Week.style.color="red"}else if(parseFloat(Week.textContent)>0){Week.style.color="green";Week.textContent="+"+Week.textContent}
Month.textContent=(data.changes.price.month*converter[currencySelected.textContent]).toFixed(2)+symbol[currencySelected.textContent];if(parseFloat(Month.textContent)<0){Month.style.color="red"}else if(parseFloat(Month.textContent)>0){Month.style.color="green";Month.textContent="+"+Month.textContent}})};function priceCheck(){if(document.querySelector("#ethereumPercent").checked===!1){if(document.querySelector(".currency-selected span").textContent=="USD")getPriceChangeEthereum();if(document.querySelector(".currency-selected span").textContent=="EUR")getPriceChangeEthereum();if(document.querySelector(".currency-selected span").textContent=="RUB")getPriceChangeEthereum();if(document.querySelector(".currency-selected span").textContent=="GBP")getPriceChangeEthereum()}
if(document.querySelector("#litecoinPercent").checked===!1){if(document.querySelector(".currency-selected span").textContent=="USD")getPriceChangeLitecoin();if(document.querySelector(".currency-selected span").textContent=="EUR")getPriceChangeLitecoin();if(document.querySelector(".currency-selected span").textContent=="RUB")getPriceChangeLitecoin();if(document.querySelector(".currency-selected span").textContent=="GBP")getPriceChangeLitecoin()}
if(document.querySelector("#bitcoinPercent").checked===!1){if(document.querySelector(".currency-selected span").textContent=="USD")getPriceChangeBitcoin();if(document.querySelector(".currency-selected span").textContent=="EUR")getPriceChangeBitcoin();if(document.querySelector(".currency-selected span").textContent=="RUB")getPriceChangeBitcoin();if(document.querySelector(".currency-selected span").textContent=="GBP")getPriceChangeBitcoin()}}
priceCheck();function percentsCheck(){if(document.querySelector("#ethereumPercent").checked===!0){if(document.querySelector(".currency-selected span").textContent=="USD")getPercentsChangeEthereum();if(document.querySelector(".currency-selected span").textContent=="EUR")getPercentsChangeEthereum();if(document.querySelector(".currency-selected span").textContent=="RUB")getPercentsChangeEthereum();if(document.querySelector(".currency-selected span").textContent=="GBP")getPercentsChangeEthereum()}
if(document.querySelector("#litecoinPercent").checked===!0){if(document.querySelector(".currency-selected span").textContent=="USD")getPercentsChangeLitecoin();if(document.querySelector(".currency-selected span").textContent=="EUR")getPercentsChangeLitecoin();if(document.querySelector(".currency-selected span").textContent=="RUB")getPercentsChangeLitecoin();if(document.querySelector(".currency-selected span").textContent=="GBP")getPercentsChangeLitecoin()}
if(document.querySelector("#bitcoinPercent").checked===!0){if(document.querySelector(".currency-selected span").textContent=="USD")getPercentsChangeBitcoin();if(document.querySelector(".currency-selected span").textContent=="EUR")getPercentsChangeBitcoin();if(document.querySelector(".currency-selected span").textContent=="RUB")getPercentsChangeBitcoin();if(document.querySelector(".currency-selected span").textContent=="GBP")getPercentsChangeBitcoin()}}
percentsCheck()
ethereumCheck.addEventListener("click",function(){if(document.querySelector("#ethereumPercent").checked===!1)priceCheck();if(document.querySelector("#ethereumPercent").checked===!0)percentsCheck()})
litecoinCheck.addEventListener("click",function(){if(document.querySelector("#litecoinPercent").checked===!1)priceCheck();if(document.querySelector("#litecoinPercent").checked===!0)percentsCheck()})
bitcoinCheck.addEventListener("click",function(){if(document.querySelector("#bitcoinPercent").checked===!1)priceCheck();if(document.querySelector("#bitcoinPercent").checked===!0)percentsCheck()})
function classRemoveAdd(){function addClass(object,cls){if(void 0===cls)return;let arr=object.className.split(" ");if(arr.some(function(elem){return elem==cls}))return;arr.push(cls);object.className=arr.join(" ")}
function removeClass(object,cls){let tempArr=object.className.split(" ");tempArr=tempArr.filter(function(word){return word!=cls});object.className=tempArr.join(" ")}
if(arguments[2]&&!arguments[1]){addClass(arguments[0],arguments[2]);return}
removeClass(arguments[0],arguments[1]);addClass(arguments[0],arguments[2])}